          
          
const cities = [
               'Oradea','Salonta','Marghita','Sacueni','Beius','Valea lui Mihai','Alesd','Stei','Vascau','Nucet',
               "Abrămuț",	
                "Aușeu",
                "Avram Iancu",
                "Balc",
                "Batăr",
                "Biharia",	
                "Boianu Mare",	
                "Borod",
                "Borș",
                "Brusturi",	
                "Budureasa",
                "Buduslău",
                "Bulz",
                "Buntești",
                "Căbești",
                "Căpâlna",
                "Cărpinet",
                "Cefa",
                "Ceica"	,
                "Cetariu",	
                "Cherechiu",	
                "Chișlaz",
                "Ciumeghiu",	
                "Câmpani",
                "Cociuba Mare",	
                "Copăcel"	,
                "Criștioru de Jos",	
                "Curățele",
                "Curtuișeni",	
                "Derna",
                "Diosig",
                "Dobrești",	
                "Drăgănești",	
                "Drăgești",	
                "Finiș",
                "Gepiu",
                "Girișu de Criș",	
                "Hidișelu de Sus",	
                "Holod",
                "Husasău de Tinca",	
                "Ineu",
                "Lazuri de Beiuș"	,
                "Lăzăreni",
                "Lugașu de Jos"	,
                "Lunca",
                "Mădăras",	
                "Măgești"	,
                "Nojorid"	,
                "Olcea",
                "Oșorhei"	,
                "Paleu",
                "Pietroasa",	
                "Pocola",
                "Pomezeu",	
                "Popești"	,
                "Răbăgani",	
                "Remetea",
                "Rieni",
                "Roșia",
                "Roșiori"	,
                "Săcădat"	,
                "Sălacea"	,
                "Sălard	",
                "Sâmbăta"	,
                "Sâniob",
                "Sânmartin"	,
                "Sânnicolau Român",	
                "Sântandrei",
                "Sârbi",
                "Spinuș",
                "Suplacu de Barcău",	
                "Șimian",
                "Șinteu",
                "Șoimi",
                "Șuncuiuș",	
                "Tarcea	",
                "Tămășeu",	
                "Tărcaia"	,
                "Tăuteu	",
                "Tileagd"	,
                "Tinca",
                "Toboliu"	,
                "Tulca",
                "Țețchea"	,
                "Uileacu de Beiuș",	
                "Vadu Crișului",
                "Viișoara",
                "Vârciorog"
              ]

              cities.sort()

    export default cities